### ISSUE TITLE
Setting seed value

### ISSUE THREAD

**Issue by holocronweaver** [clMathLibraries/clRNG#1]
How do you set a seed value in this library? Currently default `creator`s are used, and there appears to be no way to modify them since the implementation of the struct is in a *.c file. Am I overlooking a simple method? I am surprised this is not part of the intro documentation.

**Comment by holocronweaver** [comment]
Nevermind, I got it. My first read through the doc confused me about State vs. Creator - I didn't realize they were two separate structs. `clrngMrg31k3pSetBaseCreatorState` was the method I was looking for and allows setting the seed before creating streams. I think using this function in the initial example would help new users understand how to practically use the library.

**Comment by pierrelecuyer** [comment]
Jesse:

In fact there is no need to set the seed.  By doing nothing, one just 
goes ahead with the default seed, which is as good as any other seed. 
This is what I usually do.  But we can indeed add one sentence in an 
early example saying how the seed can be changed. Will do in next 
revision.  -- Pierre

On 2015-05-11 02:27, Jesse Johnson wrote:

> Nevermind, I got it. My first read through the doc confused me about 
> State vs. Creator - I didn't realize they were two separate structs. 
> |clrngMrg31k3pSetBaseCreatorState| was the method I was looking for 
> and allows setting the seed before creating streams. I think setting 
> the seed in this way for the initial example would help new users.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/clMathLibraries/clRNG/issues/1#issuecomment-100786195.Web 
> Bug from 
> https://github.com/notifications/beacon/AKp1o5sh6fEL1wunsXrwmD0D6HVLBwX0ks5oIEM2gaJpZM4EWNV_.gif

## 

Pierre L'Ecuyer, Professeur Titulaire
Chaire du Canada en Simulation et Optimisation Stochastique
CIRRELT, GERAD, and DIRO, Université de Montréal, Canada
http://www.iro.umontreal.ca/~lecuyer

**Comment by holocronweaver** [comment]
Thanks!

I am using the RNG to ensure each execution of my program produces different output. If I used the same seed every execution, each execution would produce the exact same results. Good for debugging when I need predictable outcomes, but not good for achieving my ultimate goal of unpredictable output. I am sure a large portion of users will be using RNG for the same.
