### ISSUE TITLE
seed

### ISSUE THREAD

**Issue by assemblical** [clMathLibraries/clRNG#7]
Hello everyone,

I'm currently using clRNG Mrg31k3p in my master thesis to produce random parameters for rays that are used in a ray tracer. However the generated random numbers are always the same in each execution of the program. Do I have to write my own StreamCreator to get different random numbers (and therefore different seeds) in each execution?

Best

**Comment by tingxingdong** [comment]
This is a library. Users can write their own callers (with their random seeds) to call the library routine

**Comment by kknox** [comment]
Have you read issue #1?  I believe this should answer your question.

**Comment by assemblical** [comment]
@kknox Sorry I didn't see the issue. Thanks for the hint! I'm currently using the time to set different seeds.
